site_name: The Bollnas Project
site_url: https://www.ssshhhh.com/bollnas

theme:
  name: material
  palette:
    primary: light-blue
    accent: blue
  features:
    - navigation.footer
    - content.code.copy
    - content.code.annotate
    - navigation.tracking
    - navigation.indexes
    - navigation.prune
    - navigation.top
    - toc.follow
    # - navigation.expand

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/leerobo

copyright: © 2025 Lee Robinson (leerobo)

plugins:
  - mkdocstrings
  - search
  - swagger-ui-tag:
      tryItOutEnabled: false
      supportedSubmitMethods: []
      defaultModelsExpandDepth: 0
  # - git-revision-date-localized
  - latest-git-tag
  - minify:
      minify_html: true
      minify_css: true
      minify_js: true
      htmlmin_opts:
        remove_comments: true

dev_addr: "127.0.0.1:14120"

markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.snippets
  - pymdownx.superfences
  - md_in_html
  - pymdownx.highlight:
      linenums: false
      auto_title: false
  - attr_list
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Introduction: index.md
  - Breaking Changes: important.md
  - Usage:
      - Installation: usage/installation.md
      - Configuration:
          - Environment File: usage/configuration/environment.md
          - Install Dependencies: usage/configuration/setup.md
          - Setup Database: usage/configuration/database.md
      - Add a User: usage/add-user.md
      - User Control via the CLI: usage/user-control.md
  - Customization:
      - Metadata: customization/meta.md
      - Templates: customization/templates.md
  - Development and Testing:
      - With a Local Server: development/local.md
      - With Docker: development/docker.md
      - Documentation: development/documentation.md
  - Guides and How-to's: how-to-guides.md
  - Project Organization: project-organization.md
  - Tutorials: tutorials.md
  - Deployment: deployment/deployment.md
  - API Reference: reference/api.md
  - Interactive API Docs: reference/swagger.md
  - Future Plans: future.md
  - Known Issues: known-issues.md
  - Contributing: contributing.md
  - Changelog: changelog.md
  - License: license.md
